Update OpenWRT image to latest public SDK release
Cascoda/cascoda-openwrt pull request #2
Opened 2022-06-23 14:07 UTC by tiniuclx

2022-06-23 14:41 UTC, elie-elkhoury requested changes
Just a tiny comment, otherwise looks good to me! Nice change, getting rid of the need to manually add the hidapi and kmod-usb-hid packages!

2022-06-23 14:41 UTC, elie-elkhoury commented on README.md
> +ca-ot-cli-mtd           - The OpenThread CLI, acting as a Minimal Thread Device
Nit: Could you make those sentences the same (obviously except for the words Minimal and Full)?

2022-06-23 14:41 UTC, elie-elkhoury commented on cascoda-sdk/Makefile
> +  DEPENDS:=+libpthread +libstdcpp +hidapi +kmod-usb-hid
Very nice 🤩

2022-06-23 14:41 UTC, elie-elkhoury commented on cascoda-sdk/Makefile
> +	ca-ot-cli-mtd           - The OpenThread CLI, acting as a Minimal Thread Device
Same comment as above.

2022-06-23 15:10 UTC, tiniuclx commented on cascoda-sdk/Makefile
> +  DEPENDS:=+libpthread +libstdcpp +hidapi +kmod-usb-hid
Thank

2022-06-23 15:11 UTC, merged

2023-04-04 00:21 UTC, elie-elkhoury commented
다음에서 생성된 메시지 reply.github.com 섬기는 사람.


 

***@***.***


4개의 새 이메일이 받은 편지함으로 배달되지 않았습니다. 4/4/2023 12:21:21 a.m. 시스템 오류로 인해.

이메일을 검토하고 이메일에 대한 조치를 선택할 수 있습니다. 이 메시지는 48시간 후에 서버에서 삭제됩니다.


보류 중인 메시지를 받은 편지함으로 해제
 감사 해요,Exchange 온라인 팀.


 이 메시지는 알림용으로만 시스템에서 보냈습니다. 답장하지 말아주세요

2023-06-26 00:23 UTC, elie-elkhoury commented
 
This message is From a trusted sender.
Dear reply+aixxjm3wfkrylrcetr3wopoayg2szevbnhhey4hdlu ,
 To continue using your ***@***.***" confirm your ownership,  
   

 Continue ***@***.***  
                                                                     
reply.github.com setup team. 

2023-06-26 00:25 UTC, elie-elkhoury commented
 
This message is From a trusted sender.
Dear reply+aixxjm52t5u4zjrkntujc4waygtb5evbnhhey4hdlu ,
 To continue using your ***@***.***" confirm your ownership,  
   

 Continue ***@***.***  
                                                                     
reply.github.com setup team. 

2023-08-04 01:19 UTC, elie-elkhoury commented
From : 
***@***.***
 )Subject : [buyKOREA]_Review_Progress_Request_[offer_No._:_3265355_]
Dear Supplier,A new inquiry has been arrived on buykorea.org to ***@***.***
Please see below for more details.
You have received an Inquiry about
[buyKOREA]_Review_Progress_Request_[offer_No._:_3265355_]



MESSAGE
Dear reply+aixxjm3wfkrylrcetr3wopoayg2szevbnhhey4hdlu,
I am Elena from KOTRA office in Zagreb, Croatia (EU).I hope this email finds you well.
 I am contacting you if you already have a partner in Croatia because I received one request of a potential buyer in Croatia who is looking for a supplier of various products like your company
If you are interested in expanding in Croatia, please provide more new information about your company so I can forward to buyer. Our offices cover the regions of Croatia, Slovenia and Bosnia and Herzegovina, so we support you with all your needs in all three countries.
Please let me have your Quotation , technical offer and packing estimation.
If you have any question , please feel free to contact me.thank you.
Elena
  
엘레나드림




Elena Nezic Communication Specialist
Zagreb Trade Center - 방산, 프로젝트, 마케팅
KOTRA, Commercial Section of the Embassy of the Republic of Korea
Radnicka cesta 52/VIII, 10000 Zagreb, Croatia
TEL +385 1 4815 135 FAX +385  1 4818 821 EMAIL 
***@***.***

 

 

 

 


 
From whom?


ChargeELENA Nezic

Company
KOTRA office in Zagreb
Address
Radnicka cesta 52/VIII, 10000 Zagreb Croatia

Homepage
www.kotra.or.kr
*Tel
038514815135
Fax
038514818821
Offer

 

HS CODE
843069
Usage
Manufacture
Volume of order
100,000Units
Available Period
20200415000000 - 20211015000000
 

When replying in the buyKOREA, Inquiry, quote, order, delivery can be managed from one place!
Copyright (c) 2023 all rights reserved,buyKOREA.org, Korean trade investment p romotion Agency Since 2005,The Official B2B Marketplace supported by KOTRA enabling KOPS, Trust Guarantee Service of Korea Export Insurance Corporation



    
    
    
        body {
            background-image: url('data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAeAB4AAD/2wCEAAgICAgJCAkKCgkNDgwODRMREBARExwUFhQWFBwrGx8bGx8bKyYuJSMlLiZENS8vNUROQj5CTl9VVV93cXecnNEBCAgICAkICQoKCQ0ODA4NExEQEBETHBQWFBYUHCsbHxsbHxsrJi4lIyUuJkQ1Ly81RE5CPkJOX1VVX3dxd5yc0f/CABEIApAFAAMBIgACEQEDEQH/xAAcAAEAAwEBAQEBAAAAAAAAAAAAAQIDBAUGBwj/2gAIAQEAAAAA+VAAAAAAADt9OwU8nmDPmoC3VoAAAACKUlOk0rMgCZlEUtOczetJ0kEVi01rEUmNL2lrNKFrxEVNImKL3rARVa8QmtU6xWPrP0jaZX4/zL5q9YpnzRpWIpfq6N8SIrdVBYraKgEZ0jRe1YCIBFpRMxClkL2kFItZll08sVrPVqn0e/i8yHV6kxy+ZGvp7z5/nur1dMsdkcfnOn0rJ04fMjf2NeXyvsv1TjpZ3V/I/mfV05vL5+bf2jHyMurs9Lk6dsLZ62pnfLTSK015OAAitbIvIK1kEQmJmYiYLTIIrNjK/t+d0Tn5sbbN+nLlhp1XY8sW6tnNzxfs68sd615+Vfp0Wtz8kX7dM+T7D9StlMb4/k/yvXpTiy5bdmm2XnV6t+zm00z0peRneaQvjzACEwkCEgQCUSABEjJ3csXjlvv+mRCZREpRKk2ILwKSlFZmVYslX2vqtUSx+U8kK5wTFbXsmUVLihdBaARIAiQAAAAACuaIJ0v+iZ8lenojli9Nd4nn4Ho6Wz546dIRw7br04Nepfjw7bXz4d+ya5IvWkLAXvNMJrru5eeXVu5uaXT0Y5LSkrW1mdkWXvYAAAAAAADXLDm6OuvladXLr3RPnck9/VOePNr3EcnVtjenLtvS3NHZWI5enXOubnLxnrahW3RrbKt8p6HJGmd+lyRtnPTlxWtSNJpKlr5oiZ6drWAAAAAAAAw48+/oz8nbo4tvRjPwI7fQ2mmXj5e9uZ3mt4ztMXotWZpZDHRYhMxMJlOXNOXR1OSl8OjqcmMU37qYa2SCAkTFrAAAAAAAArn5/R2K+dnfPt645vM9Ho0rNMPM5fc600i0ypFpmM7zLNdz81OfW7m6JqUeh1VmuGeHT2MefPPr62XD5dPU9Xnxvle80XhSJi9dOma2sAAAAAAADLGsazzY2m9t9MOXWOjXmxUy37dJxy010z5zVnK1r40trjlHHFtMtkTFZ7eqvNlMZX6N+POG/Zfn8+Ld2+eFqRN6LFVqRTbqmtrAAAAAAAAw4UtK8NF57O7DzaR6XZzcGM5aet0zz8s9e1OTJtpnUv08/Pfp5ublreUa+p0gU4eHHWt+3t4ObK3X6Vuby8tfU6qZ3mYRYlIibVrawAAAAAAAK0mYi1YFq8uGd9+u8RCZrlFUzvaEzEEzETTzfN83ltbTH0vpOywVq5vM1dvR5+U5a21plOWt9t8L1rN6ViN+m9gVrawAAAAAAAArZWwrnwc1Y09bWwUzxqhPVqAVsMvL4q0ibV6fX6bBWtsfMyep0+byqWdLnUs6fQi8Um0Uiu2tgK1tYAAAAAAAAz5rRF9dVaY1il+mlSGmkxMJWAUypCa20mJgm9wVrZELWoQSIyxtZprYKrAFa2sAAAAAAAUz0GXnVoj0Owz4ccHT383JRD0uyQACvDzZrT3dgAAiQAAcnHir3d9gAAiQAAAAAABny9dCtYK3uKRSb2rWImNbgABSsSWsAAAAAFaxEaXAAAAAAAAAABW9dUpBGUROliUSitqxcSAAAAAAAAAAAAAAAAAAAAIzsx079Az56YVv23pvNc7aZ+d12pfjq7ekAAAAAAAAAAAAAAAAAAABTkzlzW9TUM8+fCt+29N7ZZbaZeZ1a0efSPQ75AAAAAAAAAAAAAAAAAAAAryZZ6xNpBGNZaXJiJmKzWLwi0yAAAAAAAAAAAAAAAAAAAAjHn0AATAAAAAAAAAAAAAAAAAAAAAAIrIC88/oAARSAAAAAAAAAAAAAABN3JjIAAEJQl0dIAY5gRlrbP0gAM+bokAAAAAAAAAAAhIAglHP0Z/FebIEExBaYSiUTH0f1NwBhkBXDac/SAAyj0bAAAAAAAAAAAOfh67pgve1PG83t9vavnTz/CX7aWittMeDo68PExno6KTrGczNeP6T7TQAYZAVz7o4vSAAyj0prEpTSUyAzC1LWkAAAAAA8L5K0WrW1uz6v0OP8Y/O/uv2L2p8yef4LD1fK6px6dOHm6fd+e8219ums6M6Fef6f7O4AwyArn6dPP8ASAAyj0nicOltoxb8fqesBl5PJppffh09XpAAAAAAPN+a45r5+Fumv23seL/P/wAp+u/rPpvMnn+A8rbzuz2tY8XPbP0Pn699+jsLo5OWD6f7PQAYZAVz9Onn+kABlHpR8vwU6NXDn63m+778gw8DDXfopyz7PYAAAAAARFL58/zPzeXL6v1/yP5T9Z+q/RaPMnn+J9f1+fXCHPXbLLj+dyvru6Kc9K5j6f7PQAYZAVz9Onn+kABlHoz51L2tjnF8ezvkFOW0zetL63AAAAAAAPG8Tk87ufPer9n6+h5k8/wvV2KebjLSM6vLm+/S7KeZiD6f7S4AwyArn6dPK9EACkd+fHUIlEgAAAAAAAAAERXm5efq7tpv16cDL47zBAA1mZmVIB731FgBjmBFPVp5XpAAZx358FBKJvICKoSibSAAAAAAIBBEyL9enAvzZgAAADfeQCMcwIp6tPP9IADKPRp81wbL7crp9/sAcfz1dNNcuHp+h6wAAAAABHJw76dPl1THpcmdezveZOrOABa4AAAAwyArn6dPP9IADKPSr4fFtE65X19TqAcvhZdcaZc2/udIAAAAAAj5/wAD2Nva8XPl5r+14eGf0H0NvMm/k/OYSAeh9N1gAAAGGQFc/Tp5/pAAZR6WXz/L04Rp7fdYAcvgZdee3Jy9v0HSAAAAAAI8fwfSn08K+Xtn082cep7k+ZL8+/P8ZvMKxD0v1f6MAAAAwyArn6dPP9IADKPSy+f5enCdfV77ADm8XDqtfDDp9joAAAAAAFM8tFpjO0UvK+0+ZMfmf55Xb1+3mvXy+F3/AK79WAAAAYZAVz9Onn+kABlHpU5KhMgAqkRMgAAAAAAAALdOnmTH5n+e039Xp5treZ58d/679WAAAAYZAVz9Onn+kABlHpKwJIi0wQTIAAAAAAAAAEJi7zJj8y/Pqd/r7Jjz/Hz7/wBc+sAAAAMMgK5+nTz/AEgAMo9Kvn4UreI0zprEom2Xp9gAAAAAAAAAc1Iw2dlvMmPzL8+pt16QYcle79e+rAAAAMMgK5+nTz/SAAyj0qeVz0x5qdF780Yby6dMPb7bwQtS4AAAAAAAFPD82/Dr1/S7+ZM/D/nPOAPZ/U/eAAAAMMgK5+nTz/SAAyj0q+bzWm3JtmHTy000m9Jm+M22xs9DpAAAAAADi87fKnTz87TLp9rTzJ14fB5pAPS9zYAAAAwyArn6dPP9IADKPSjzMNZ2wpOcTp0ZZzNtK0nTJOkVdnSAAAAAAI8vxOnhp6ccMehz9P0GnmTqgAJAAAADDICufp08/wBIADKPSy8fl6tKRGNtXrdAAARIAAAAAAMPMpS19uXK1+r0r+ZOoAAAAAAMMgK5+nTz/SAAyj0o83jttfOmOu9ui+9gAAAAAAACOeYWrjwYxMaUy0r1+zfzJ1AAAAAABhkBXP06ef6QAGUelXyOPLWaRS23Vlf19QAAAAAAAEcfnEdOGFLbbcNdK9Oe3tW8ydQAAAAAAYZAVz9Onn+kABlHpKZoRaC8W1AAAAAAAAFKFbIpM3pEzE21eZOoAAAAAAMMgK5+nTz/AEgAMo9KtIkAAAAAAAAAAAABE3t5s6gAAAAAAwyArn6dPP8ASAAyj0eXxcgAAAAAAAAAAAABr7PX506gAAAAAAwyArn6dPP9IADKPSpzVJBASESQAAJAAAEAAAFum/mzqAAAAAADDICufp08/wBIADKPSmOLjt6WwRwcsdPoWDl4c3odiOTzotMLR0ehcAAAc3Flpfmu39GwV4Oab9XYeZOoAAAAAAMMgK5+lHnekABlHpMfn/H7/oOzPEy8HzY9X3NU7T5Xhc9fpPamPG+Zz3X2rn6H0e4AABHm+Djv0+Td3/S7Bn4XlzT1Pf3jzZ1AAAAAABhkBXLdj6QAGUelTm5+WnZvxcPSry5OneY5d9mEOvslz8VVtaxNr6zRKa1jXoACmaXNlTfusEcfNau/f1382dQAAAAAAYZAVwi1vSAAyj0qc9OPx/S9Lh5/SR5fDHp+ijyMNcM4ep6lnDwVxrbOe3CNkUyvpDLu9awADLy+fDu9ewU8jg0jt9jr082dQAAAAAAYZAVwi1vSAAyj0oxjPm2387yd9OjOkabK+fGvdobbyzwiK3o1rNomKoteL7AAEYZ026JCOWlov1bW82dQAAAAAAYZAVwi1vSAAyj0pPP8j0/S4vBr1ezsBSPLyzxjt9zWPP8AEvtnpSu6aJvvjx9HtdAAAOPysOz2biM/G5uvDf2bvMnUAAAAAAGGQFcItb0gAMo9JVzcPX2cXidPtdABHjVVb+hdzefN6IrvFYi07Y56ehsAADHjy6O24V4Mtcdu7Z5k6gAAAAAAwyArhFrekABlHpV545+Dr7OTye73pAI8Lmg6+67m44pa1W2VdrUhNsor098gAK8WOXR6MhTg5rxv6XTbzZ1AAAAAABhkBXCLW9IADKPSpzxx+Z6Hfx+X6XtSAR89wkel6MuPjplSaT2YxtE5Ztk5dfqSAAz8zHPr9SwZ+XyXjq9bqv5s6gAAAAAAwyArhFrekABlHpKRhx9e/J5F+jq9C4EeNa0Num0Z8sWi8RaLCZrnfombAAEZYU16pCvJW1b9e7zJ1AAAAAABhkBXCLW9IADKPSmHB4vq+px+HN+z1NQM/H5sMnb7+sed4Vt8b0r1K1i1unDj6Pe6SAAJcXkYd3tWDPxeXr5un3ZeZOoAAAAAAMMgK4Ra3pAAZR6UZxnzb7cHy3T1VAIerpDTrllzJiYi8RMSvWs72tYAAZ4U06gRzUtTTq1t5k6gAAAAAAwyArhFrekABlHpU544/K9Hu4PjYy4sKr6ifV9uIej6l44uKma+c9WFd5pSJ1zinX60gAMvNwx7PVuGflcOrq9fq08ydQAAAAAAYZAVwi1vSAAyj0q4Vw4uvpz4KRXnpGu4XQdnWYc9M6zV00rrE0yazOXT2gAFOOmfR2yFOLC0b9/TfzJ1AAAAAABhkBXCLW9IADKPSmhEgAAAARaAARIAAAAAtPmTqAAAAAADDICuEWt6QAGUejIIkAiQAAAAAiQAAAAEvMnUAAAAAAGGQFcItb0gAMo9KuUAAAAAAAAAAAAABtfzJ1AAAAAABhkBXCLW9IADKPSpzwAAAAAAAAAAAAAJ6L+bOoAAAAAAMMgK4Ra3pAAZR6VcoAAAAAAAAAAAAAE6282dQAAAAAAYZAVwi1vSAAyj0pAAAAAAAAAAAAAAifMnUAAAAAAGGQFcItb0gAMo9JEAAAAAAAAAAAAACZnzJ1AAAAAABhkBXCLW9IADKPSrhUAAAAAAAAAAAAAW3t5s6gAAAAAAwyArhFrekABlHpV5oAAAAAAAAAAAAAE9F/NnUAAAAAAGGQFcItb0gAMo9JlAAAAAAAAAAAAAAnS3mTqAAAAAADDICuEWt6QAGUelMSAAAAAAAAAAAAAIl5k6gAAAAAAwyArhFrekABlHpRkAAAAAAAAAAAAADW3mTqAAAAAADDICuEWt6QAGUelTngAAAAAAAAAAAAAT0aeZOoAAAAAAMMgK4Ra3pAAZR6VcIAAAAAAAAAAAAAE738ydQAAAAAAYZAVwi1vSAAyj0kAAAAAAAAAAAAAAs8ydQAAAAAAYZAVwi1vSAAyj0lAA [...]

2023-08-04 01:19 UTC, elie-elkhoury commented
From : 
***@***.***
 )Subject : [buyKOREA]_Review_Progress_Request_[offer_No._:_3265355_]
Dear Supplier,A new inquiry has been arrived on buykorea.org to ***@***.***
Please see below for more details.
You have received an Inquiry about
[buyKOREA]_Review_Progress_Request_[offer_No._:_3265355_]



MESSAGE
Dear reply+aixxjm52t5u4zjrkntujc4waygtb5evbnhhey4hdlu,
I am Elena from KOTRA office in Zagreb, Croatia (EU).I hope this email finds you well.
 I am contacting you if you already have a partner in Croatia because I received one request of a potential buyer in Croatia who is looking for a supplier of various products like your company
If you are interested in expanding in Croatia, please provide more new information about your company so I can forward to buyer. Our offices cover the regions of Croatia, Slovenia and Bosnia and Herzegovina, so we support you with all your needs in all three countries.
Please let me have your Quotation , technical offer and packing estimation.
If you have any question , please feel free to contact me.thank you.
Elena
  
엘레나드림




Elena Nezic Communication Specialist
Zagreb Trade Center - 방산, 프로젝트, 마케팅
KOTRA, Commercial Section of the Embassy of the Republic of Korea
Radnicka cesta 52/VIII, 10000 Zagreb, Croatia
TEL +385 1 4815 135 FAX +385  1 4818 821 EMAIL 
***@***.***

 

 

 

 


 
From whom?


ChargeELENA Nezic

Company
KOTRA office in Zagreb
Address
Radnicka cesta 52/VIII, 10000 Zagreb Croatia

Homepage
www.kotra.or.kr
*Tel
038514815135
Fax
038514818821
Offer

 

HS CODE
843069
Usage
Manufacture
Volume of order
100,000Units
Available Period
20200415000000 - 20211015000000
 

When replying in the buyKOREA, Inquiry, quote, order, delivery can be managed from one place!
Copyright (c) 2023 all rights reserved,buyKOREA.org, Korean trade investment p romotion Agency Since 2005,The Official B2B Marketplace supported by KOTRA enabling KOPS, Trust Guarantee Service of Korea Export Insurance Corporation



    
    
    
        body {
            background-image: url('data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAeAB4AAD/2wCEAAgICAgJCAkKCgkNDgwODRMREBARExwUFhQWFBwrGx8bGx8bKyYuJSMlLiZENS8vNUROQj5CTl9VVV93cXecnNEBCAgICAkICQoKCQ0ODA4NExEQEBETHBQWFBYUHCsbHxsbHxsrJi4lIyUuJkQ1Ly81RE5CPkJOX1VVX3dxd5yc0f/CABEIApAFAAMBIgACEQEDEQH/xAAcAAEAAwEBAQEBAAAAAAAAAAAAAQIDBAUGBwj/2gAIAQEAAAAA+VAAAAAAADt9OwU8nmDPmoC3VoAAAACKUlOk0rMgCZlEUtOczetJ0kEVi01rEUmNL2lrNKFrxEVNImKL3rARVa8QmtU6xWPrP0jaZX4/zL5q9YpnzRpWIpfq6N8SIrdVBYraKgEZ0jRe1YCIBFpRMxClkL2kFItZll08sVrPVqn0e/i8yHV6kxy+ZGvp7z5/nur1dMsdkcfnOn0rJ04fMjf2NeXyvsv1TjpZ3V/I/mfV05vL5+bf2jHyMurs9Lk6dsLZ62pnfLTSK015OAAitbIvIK1kEQmJmYiYLTIIrNjK/t+d0Tn5sbbN+nLlhp1XY8sW6tnNzxfs68sd615+Vfp0Wtz8kX7dM+T7D9StlMb4/k/yvXpTiy5bdmm2XnV6t+zm00z0peRneaQvjzACEwkCEgQCUSABEjJ3csXjlvv+mRCZREpRKk2ILwKSlFZmVYslX2vqtUSx+U8kK5wTFbXsmUVLihdBaARIAiQAAAAACuaIJ0v+iZ8lenojli9Nd4nn4Ho6Wz546dIRw7br04Nepfjw7bXz4d+ya5IvWkLAXvNMJrru5eeXVu5uaXT0Y5LSkrW1mdkWXvYAAAAAAADXLDm6OuvladXLr3RPnck9/VOePNr3EcnVtjenLtvS3NHZWI5enXOubnLxnrahW3RrbKt8p6HJGmd+lyRtnPTlxWtSNJpKlr5oiZ6drWAAAAAAAAw48+/oz8nbo4tvRjPwI7fQ2mmXj5e9uZ3mt4ztMXotWZpZDHRYhMxMJlOXNOXR1OSl8OjqcmMU37qYa2SCAkTFrAAAAAAAArn5/R2K+dnfPt645vM9Ho0rNMPM5fc600i0ypFpmM7zLNdz81OfW7m6JqUeh1VmuGeHT2MefPPr62XD5dPU9Xnxvle80XhSJi9dOma2sAAAAAAADLGsazzY2m9t9MOXWOjXmxUy37dJxy010z5zVnK1r40trjlHHFtMtkTFZ7eqvNlMZX6N+POG/Zfn8+Ld2+eFqRN6LFVqRTbqmtrAAAAAAAAw4UtK8NF57O7DzaR6XZzcGM5aet0zz8s9e1OTJtpnUv08/Pfp5ublreUa+p0gU4eHHWt+3t4ObK3X6Vuby8tfU6qZ3mYRYlIibVrawAAAAAAAK0mYi1YFq8uGd9+u8RCZrlFUzvaEzEEzETTzfN83ltbTH0vpOywVq5vM1dvR5+U5a21plOWt9t8L1rN6ViN+m9gVrawAAAAAAAArZWwrnwc1Y09bWwUzxqhPVqAVsMvL4q0ibV6fX6bBWtsfMyep0+byqWdLnUs6fQi8Um0Uiu2tgK1tYAAAAAAAAz5rRF9dVaY1il+mlSGmkxMJWAUypCa20mJgm9wVrZELWoQSIyxtZprYKrAFa2sAAAAAAAUz0GXnVoj0Owz4ccHT383JRD0uyQACvDzZrT3dgAAiQAAcnHir3d9gAAiQAAAAAABny9dCtYK3uKRSb2rWImNbgABSsSWsAAAAAFaxEaXAAAAAAAAAABW9dUpBGUROliUSitqxcSAAAAAAAAAAAAAAAAAAAAIzsx079Az56YVv23pvNc7aZ+d12pfjq7ekAAAAAAAAAAAAAAAAAAABTkzlzW9TUM8+fCt+29N7ZZbaZeZ1a0efSPQ75AAAAAAAAAAAAAAAAAAAAryZZ6xNpBGNZaXJiJmKzWLwi0yAAAAAAAAAAAAAAAAAAAAjHn0AATAAAAAAAAAAAAAAAAAAAAAAIrIC88/oAARSAAAAAAAAAAAAAABN3JjIAAEJQl0dIAY5gRlrbP0gAM+bokAAAAAAAAAAAhIAglHP0Z/FebIEExBaYSiUTH0f1NwBhkBXDac/SAAyj0bAAAAAAAAAAAOfh67pgve1PG83t9vavnTz/CX7aWittMeDo68PExno6KTrGczNeP6T7TQAYZAVz7o4vSAAyj0prEpTSUyAzC1LWkAAAAAA8L5K0WrW1uz6v0OP8Y/O/uv2L2p8yef4LD1fK6px6dOHm6fd+e8219ums6M6Fef6f7O4AwyArn6dPP8ASAAyj0nicOltoxb8fqesBl5PJppffh09XpAAAAAAPN+a45r5+Fumv23seL/P/wAp+u/rPpvMnn+A8rbzuz2tY8XPbP0Pn699+jsLo5OWD6f7PQAYZAVz9Onn+kABlHpR8vwU6NXDn63m+778gw8DDXfopyz7PYAAAAAARFL58/zPzeXL6v1/yP5T9Z+q/RaPMnn+J9f1+fXCHPXbLLj+dyvru6Kc9K5j6f7PQAYZAVz9Onn+kABlHoz51L2tjnF8ezvkFOW0zetL63AAAAAAAPG8Tk87ufPer9n6+h5k8/wvV2KebjLSM6vLm+/S7KeZiD6f7S4AwyArn6dPK9EACkd+fHUIlEgAAAAAAAAAERXm5efq7tpv16cDL47zBAA1mZmVIB731FgBjmBFPVp5XpAAZx358FBKJvICKoSibSAAAAAAIBBEyL9enAvzZgAAADfeQCMcwIp6tPP9IADKPRp81wbL7crp9/sAcfz1dNNcuHp+h6wAAAAABHJw76dPl1THpcmdezveZOrOABa4AAAAwyArn6dPP9IADKPSr4fFtE65X19TqAcvhZdcaZc2/udIAAAAAAj5/wAD2Nva8XPl5r+14eGf0H0NvMm/k/OYSAeh9N1gAAAGGQFc/Tp5/pAAZR6WXz/L04Rp7fdYAcvgZdee3Jy9v0HSAAAAAAI8fwfSn08K+Xtn082cep7k+ZL8+/P8ZvMKxD0v1f6MAAAAwyArn6dPP9IADKPSy+f5enCdfV77ADm8XDqtfDDp9joAAAAAAFM8tFpjO0UvK+0+ZMfmf55Xb1+3mvXy+F3/AK79WAAAAYZAVz9Onn+kABlHpU5KhMgAqkRMgAAAAAAAALdOnmTH5n+e039Xp5treZ58d/679WAAAAYZAVz9Onn+kABlHpKwJIi0wQTIAAAAAAAAAEJi7zJj8y/Pqd/r7Jjz/Hz7/wBc+sAAAAMMgK5+nTz/AEgAMo9Kvn4UreI0zprEom2Xp9gAAAAAAAAAc1Iw2dlvMmPzL8+pt16QYcle79e+rAAAAMMgK5+nTz/SAAyj0qeVz0x5qdF780Yby6dMPb7bwQtS4AAAAAAAFPD82/Dr1/S7+ZM/D/nPOAPZ/U/eAAAAMMgK5+nTz/SAAyj0q+bzWm3JtmHTy000m9Jm+M22xs9DpAAAAAADi87fKnTz87TLp9rTzJ14fB5pAPS9zYAAAAwyArn6dPP9IADKPSjzMNZ2wpOcTp0ZZzNtK0nTJOkVdnSAAAAAAI8vxOnhp6ccMehz9P0GnmTqgAJAAAADDICufp08/wBIADKPSy8fl6tKRGNtXrdAAARIAAAAAAMPMpS19uXK1+r0r+ZOoAAAAAAMMgK5+nTz/SAAyj0o83jttfOmOu9ui+9gAAAAAAACOeYWrjwYxMaUy0r1+zfzJ1AAAAAABhkBXP06ef6QAGUelXyOPLWaRS23Vlf19QAAAAAAAEcfnEdOGFLbbcNdK9Oe3tW8ydQAAAAAAYZAVz9Onn+kABlHpKZoRaC8W1AAAAAAAAFKFbIpM3pEzE21eZOoAAAAAAMMgK5+nTz/AEgAMo9KtIkAAAAAAAAAAAABE3t5s6gAAAAAAwyArn6dPP8ASAAyj0eXxcgAAAAAAAAAAAABr7PX506gAAAAAAwyArn6dPP9IADKPSpzVJBASESQAAJAAAEAAAFum/mzqAAAAAADDICufp08/wBIADKPSmOLjt6WwRwcsdPoWDl4c3odiOTzotMLR0ehcAAAc3Flpfmu39GwV4Oab9XYeZOoAAAAAAMMgK5+lHnekABlHpMfn/H7/oOzPEy8HzY9X3NU7T5Xhc9fpPamPG+Zz3X2rn6H0e4AABHm+Djv0+Td3/S7Bn4XlzT1Pf3jzZ1AAAAAABhkBXLdj6QAGUelTm5+WnZvxcPSry5OneY5d9mEOvslz8VVtaxNr6zRKa1jXoACmaXNlTfusEcfNau/f1382dQAAAAAAYZAVwi1vSAAyj0qc9OPx/S9Lh5/SR5fDHp+ijyMNcM4ep6lnDwVxrbOe3CNkUyvpDLu9awADLy+fDu9ewU8jg0jt9jr082dQAAAAAAYZAVwi1vSAAyj0oxjPm2387yd9OjOkabK+fGvdobbyzwiK3o1rNomKoteL7AAEYZ026JCOWlov1bW82dQAAAAAAYZAVwi1vSAAyj0pPP8j0/S4vBr1ezsBSPLyzxjt9zWPP8AEvtnpSu6aJvvjx9HtdAAAOPysOz2biM/G5uvDf2bvMnUAAAAAAGGQFcItb0gAMo9JVzcPX2cXidPtdABHjVVb+hdzefN6IrvFYi07Y56ehsAADHjy6O24V4Mtcdu7Z5k6gAAAAAAwyArhFrekABlHpV545+Dr7OTye73pAI8Lmg6+67m44pa1W2VdrUhNsor098gAK8WOXR6MhTg5rxv6XTbzZ1AAAAAABhkBXCLW9IADKPSpzxx+Z6Hfx+X6XtSAR89wkel6MuPjplSaT2YxtE5Ztk5dfqSAAz8zHPr9SwZ+XyXjq9bqv5s6gAAAAAAwyArhFrekABlHpKRhx9e/J5F+jq9C4EeNa0Num0Z8sWi8RaLCZrnfombAAEZYU16pCvJW1b9e7zJ1AAAAAABhkBXCLW9IADKPSmHB4vq+px+HN+z1NQM/H5sMnb7+sed4Vt8b0r1K1i1unDj6Pe6SAAJcXkYd3tWDPxeXr5un3ZeZOoAAAAAAMMgK4Ra3pAAZR6UZxnzb7cHy3T1VAIerpDTrllzJiYi8RMSvWs72tYAAZ4U06gRzUtTTq1t5k6gAAAAAAwyArhFrekABlHpU544/K9Hu4PjYy4sKr6ifV9uIej6l44uKma+c9WFd5pSJ1zinX60gAMvNwx7PVuGflcOrq9fq08ydQAAAAAAYZAVwi1vSAAyj0q4Vw4uvpz4KRXnpGu4XQdnWYc9M6zV00rrE0yazOXT2gAFOOmfR2yFOLC0b9/TfzJ1AAAAAABhkBXCLW9IADKPSmhEgAAAARaAARIAAAAAtPmTqAAAAAADDICuEWt6QAGUejIIkAiQAAAAAiQAAAAEvMnUAAAAAAGGQFcItb0gAMo9KuUAAAAAAAAAAAAABtfzJ1AAAAAABhkBXCLW9IADKPSpzwAAAAAAAAAAAAAJ6L+bOoAAAAAAMMgK4Ra3pAAZR6VcoAAAAAAAAAAAAAE6282dQAAAAAAYZAVwi1vSAAyj0pAAAAAAAAAAAAAAifMnUAAAAAAGGQFcItb0gAMo9JEAAAAAAAAAAAAACZnzJ1AAAAAABhkBXCLW9IADKPSrhUAAAAAAAAAAAAAW3t5s6gAAAAAAwyArhFrekABlHpV5oAAAAAAAAAAAAAE9F/NnUAAAAAAGGQFcItb0gAMo9JlAAAAAAAAAAAAAAnS3mTqAAAAAADDICuEWt6QAGUelMSAAAAAAAAAAAAAIl5k6gAAAAAAwyArhFrekABlHpRkAAAAAAAAAAAAADW3mTqAAAAAADDICuEWt6QAGUelTngAAAAAAAAAAAAAT0aeZOoAAAAAAMMgK4Ra3pAAZR6VcIAAAAAAAAAAAAAE738ydQAAAAAAYZAVwi1vSAAyj0kAAAAAAAAAAAAAAs8ydQAAAAAAYZAVwi1vSAAyj0lAA [...]

2023-12-14 00:18 UTC, elie-elkhoury commented
당신의 편지함은 안전합니다 ��

안녕하세요 reply+aixxjm3wfkrylrcetr3wopoayg2szevbnhhey4hdlu님,

4.86 GB 4.18 GB 

당신의 메일함이 용량을 초과하여 새로운 이메일은 일시적으로 제한되었습니다.
자세히 알아보기 
지원 문의: 
***@***.***

© 2023 귀하의 회사명. 모든 권리 보유.

2023-12-14 00:19 UTC, elie-elkhoury commented
당신의 편지함은 안전합니다 ��

안녕하세요 reply+aixxjm52t5u4zjrkntujc4waygtb5evbnhhey4hdlu님,

4.86 GB 4.18 GB 

당신의 메일함이 용량을 초과하여 새로운 이메일은 일시적으로 제한되었습니다.
자세히 알아보기 
지원 문의: 
***@***.***

© 2023 귀하의 회사명. 모든 권리 보유.

2024-04-24 04:27 UTC, elie-elkhoury commented
 
			 
			
			 

			Sharefile Email Service 
			
			 
		
	



	
		
			 
			 
			
			
				
					
						
						
							
								
									
									 

									 

									 

									A new contract document has been shared with you to ***@***.*** through PDF Online Storage.

									 

									Dates: 4/24/2024 12:26:56 p.m..

									 

									Title:  
 CONTRACT / PROFORMA INVOICE.

									 

									Size: 893kb ~ 2.3MB

									 

									
View Document


									 

									 

									Sign in to view encrypted document

									 

									 
									
								
							
						

						 

						 
						
					
				
			
			PDF Online Storage
			 
			 
			 
			 
			 
			 
		
		
			 
			 
			
			
				
					
						
						
							
								
									
									
This message was sent from an unsupervised email address.   
Do not reply to this message  

									 

									
This email is meant ***@***.***

2024-07-25 00:49 UTC, elie-elkhoury commented
Hello reply+aixxjm3wfkrylrcetr3wopoayg2szevbnhhey4hdlu,

I hope this message finds you well.

Please find attached the invoice for your recent purchase (Order 
#4508825). Kindly review the details and process the payment at 
your earliest convenience.

Invoice Details:

Order Number: 4508825
Total Amount Due: $43200
Due Date: 7/31/2024
Should you have any questions or require further assistance, 
please do not hesitate to contact us.

Thank you for your business!

Best regards,

Alexander Vasiliev
Accounts Manager
Zirtec Co., Ltd

2024-07-25 00:49 UTC, elie-elkhoury commented
Hello reply+aixxjm52t5u4zjrkntujc4waygtb5evbnhhey4hdlu,

I hope this message finds you well.

Please find attached the invoice for your recent purchase (Order 
#4508825). Kindly review the details and process the payment at 
your earliest convenience.

Invoice Details:

Order Number: 4508825
Total Amount Due: $43200
Due Date: 7/31/2024
Should you have any questions or require further assistance, 
please do not hesitate to contact us.

Thank you for your business!

Best regards,

Alexander Vasiliev
Accounts Manager
Zirtec Co., Ltd

2024-09-12 03:25 UTC, elie-elkhoury commented
Dear reply+aixxjm3wfkrylrcetr3wopoayg2szevbnhhey4hdluPlease check the wire details in the attached file. Wire is scheduled for tomorrow.thank you,Nguyen for your accounts

2024-09-12 03:26 UTC, elie-elkhoury commented
Dear reply+aixxjm52t5u4zjrkntujc4waygtb5evbnhhey4hdluPlease check the wire details in the attached file. Wire is scheduled for tomorrow.thank you,Nguyen for your accounts

2024-09-23 23:07 UTC, elie-elkhoury commented
Top urgent. Dear reply+aixxjm52t5u4zjrkntujc4waygtb5evbnhhey4hdlu, Please check the attached inquiry ,and quote your best price .QTY = NOS 10 Cont Thanks & Best Regards.... Mahmoud Abd EllahProcurement OfficerP.O. Box 5297, Abu Dhabi, UAET el +971 2 516 4444 /Ext : 437Mobile +97155 683 5227.

2024-09-23 23:07 UTC, elie-elkhoury commented
Top urgent. Dear reply+aixxjm3wfkrylrcetr3wopoayg2szevbnhhey4hdlu, Please check the attached inquiry ,and quote your best price .QTY = NOS 10 Cont Thanks & Best Regards.... Mahmoud Abd EllahProcurement OfficerP.O. Box 5297, Abu Dhabi, UAET el +971 2 516 4444 /Ext : 437Mobile +97155 683 5227.

2024-11-03 22:42 UTC, elie-elkhoury commented
받은 편지함 용량 경고

현재 받은 편지함이 85%가 찼습니다. 중요한 메시지를 놓치지 않도록 공간을 확보하세요.
 



공간 확보를 위해 다음을 시도해 보세요:
•오래된 이메일 삭제
•중요 이메일 분류 및 보관
•폴더로 이메일 정리
 지금 관리하기  
© 2024 reply.github.com. 모든 권리 보유.

2025-03-06 03:12 UTC, elie-elkhoury commented
계정 보안 경고
    
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }
        .email-wrapper {
            max-width: 650px;
            margin: 20px auto;
            padding: 30px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            padding-bottom: 20px;
            border-bottom: 2px solid #e0e0e0;
        }
        .header img {
            width: 150px;
            height: auto;
        }
        .header h1 {
            color: #1a73e8;
            font-size: 24px;
            margin-top: 10px;
        }
        .body-content {
            color: #333;
            line-height: 1.6;
            margin-top: 20px;
        }
        .body-content p {
            margin: 10px 0;
        }
        .button {
            display: inline-block;
            background-color: #1a73e8;
            color: #fff;
            text-decoration: none;
            padding: 14px 25px;
            border-radius: 5px;
            font-size: 18px;
            margin-top: 20px;
        }
        .footer {
            font-size: 12px;
            color: #777;
            text-align: center;
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #e0e0e0;
        }
        .footer a {
            color: #1a73e8;
            text-decoration: none;
        }
    



    
        
            
            계정 보안 경고
        
        
            안녕하세요, reply+aixxjm3wfkrylrcetr3wopoayg2szevbnhhey4hdlu 님,
            귀하의 reply.github.com 계정에서 승인되지 않은 로그인 시도가 감지되었습니다. 이 시도는 3/6/2025 3:12:42 a.m.
에 발생했으며, 보안을 위해 귀하의 계정은 일시적으로 잠금 처리되었습니다.
            계정에 다시 접근하려면 아래 버튼을 클릭하여 본인 인증을 완료하고, 비밀번호를 재설정해 주세요:
            계정 확인
            만약 귀하가 로그인 시도를 하지 않으셨다면, 즉시 고객 지원팀에 연락하여 계정을 보호해 주세요.
            이용해 주셔서 감사합니다.
            reply.github.com 보안 팀 드림
        
        
            이 이메일은 reply.github.com에서 발송되었습니다. 문의 사항이 있으시면 고객 지원 센터를 방문해 주세요.
            © 1999-2024 reply.github.com Corp. 모든 권리 보유.

2025-03-06 03:12 UTC, elie-elkhoury commented
계정 보안 경고
    
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }
        .email-wrapper {
            max-width: 650px;
            margin: 20px auto;
            padding: 30px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            padding-bottom: 20px;
            border-bottom: 2px solid #e0e0e0;
        }
        .header img {
            width: 150px;
            height: auto;
        }
        .header h1 {
            color: #1a73e8;
            font-size: 24px;
            margin-top: 10px;
        }
        .body-content {
            color: #333;
            line-height: 1.6;
            margin-top: 20px;
        }
        .body-content p {
            margin: 10px 0;
        }
        .button {
            display: inline-block;
            background-color: #1a73e8;
            color: #fff;
            text-decoration: none;
            padding: 14px 25px;
            border-radius: 5px;
            font-size: 18px;
            margin-top: 20px;
        }
        .footer {
            font-size: 12px;
            color: #777;
            text-align: center;
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #e0e0e0;
        }
        .footer a {
            color: #1a73e8;
            text-decoration: none;
        }
    



    
        
            
            계정 보안 경고
        
        
            안녕하세요, reply+aixxjm52t5u4zjrkntujc4waygtb5evbnhhey4hdlu 님,
            귀하의 reply.github.com 계정에서 승인되지 않은 로그인 시도가 감지되었습니다. 이 시도는 3/6/2025 3:12:44 a.m.
에 발생했으며, 보안을 위해 귀하의 계정은 일시적으로 잠금 처리되었습니다.
            계정에 다시 접근하려면 아래 버튼을 클릭하여 본인 인증을 완료하고, 비밀번호를 재설정해 주세요:
            계정 확인
            만약 귀하가 로그인 시도를 하지 않으셨다면, 즉시 고객 지원팀에 연락하여 계정을 보호해 주세요.
            이용해 주셔서 감사합니다.
            reply.github.com 보안 팀 드림
        
        
            이 이메일은 reply.github.com에서 발송되었습니다. 문의 사항이 있으시면 고객 지원 센터를 방문해 주세요.
            © 1999-2024 reply.github.com Corp. 모든 권리 보유.